jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout repository

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Install Node.js version 16

      - name: Install Dependencies
        run: npm install  # Run shell command to install dependencies

      - name: Run Tests
        run: npm test  # Run tests
